### ISSUE TITLE
add documentation what Close and Reset are supposed to do

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-stream-muxer#13]
`Reset` was recently (be2992bb959db6a29d3783af04e47893cdffd3c6) added to the `Stream` interface, but it's not clear what the expected behavior is.

We should describe that in the interface. Furthermore, `Close` is also an ambiguous term, and needs an explanation as well.

For example in QUIC, `Close` closes the stream in the write-direction, and `Reset` closes the stream in read-direction.

**Comment by Stebalien** [comment]
> For example in QUIC, Close closes the stream in the write-direction, and Reset closes the stream in read-direction.

This. @whyrusleeping added this method because yamux has this same behavior and it turns out we've been half-closing our streams. This often didn't make a difference but was the ultimate cause of a rather nasty bitswap bug (https://github.com/ipfs/go-ipfs/issues/3651#issuecomment-315580747).

**Comment by marten-seemann** [comment]
That's great news! Having matching interfaces here will reduce a lot of friction with the QUIC integration I've been working on.
