### ISSUE TITLE
Please converge with https://github.com/libp2p/interface-stream-muxer

### ISSUE THREAD

**Issue by daviddias** [libp2p/go-stream-muxer#20]
https://github.com/libp2p/interface-stream-muxer

**Comment by Stebalien** [comment]
Which part specifically? This package implements everything (plus a little extra because, e.g., `io.ReadWriteCloser` isn't sufficient for a stream interface).

**Comment by daviddias** [comment]
I believe that I opened this issue after a convo about updating https://github.com/libp2p/interface-stream-muxer#api to make sure it captures the latest go interface or at least points to where to find it.

**Comment by raulk** [comment]
Do we still think interfaces across implementations should be at absolute parity? My thought (headline) is: implementors should be free to choose interface details that are most idiomatic in their language, as long as they adhere to the overall conceptual map of libp2p.

**Comment by raulk** [comment]
Gonna close for now, but please reopen if you feel strongly about addressing this in the near future.
