### ISSUE TITLE
update yamux

### ISSUE THREAD

**Issue by jbenet** [libp2p/go-stream-muxer#4]
yamux has had some improvements, namely:
- https://github.com/hashicorp/yamux/pull/21#event-476975308

cc @whyrusleeping

**Comment by gaboose** [comment]
Be careful. I naively tried to change the import paths from `github.com/jbenet/go-stream-muxer/Godeps/_workspace/src/github.com/hashicorp/yamux` to `github.com/hashicorp/yamux` and got `OpenStream()` erroring out with `connection write timeout` sometimes.

Adding default [ConnectionWriteTimeout](https://github.com/hashicorp/yamux/blob/df949784da9ed028ee76df44652e42d37a09d7e4/mux.go#L43) to [DefaultTransport](https://github.com/jbenet/go-stream-muxer/blob/e2e261765847234749629e0190fef193a4548303/yamux/yamux.go#L79) fixes it, but I'd vote to avoid manual config syncs like this. Is there a reason you don't have a `DefaultTransport()` function that just points to hashicorp's [`DefaultConfig()`](https://github.com/hashicorp/yamux/blob/df949784da9ed028ee76df44652e42d37a09d7e4/mux.go#L38)?

**Comment by raulk** [comment]
Ever since this issue was opened, we forked yamux and additional improvements of our own accord: https://github.com/whyrusleeping/yamux.
